/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");


    }


    @Test void jsonFileObjectTest(){


        ArrayList<Quotes> quotes= new ArrayList<>();

        try {
            FileReader jsonFile = new FileReader("src/main/resources/recentquotes.json");
            quotes = App.readJson(jsonFile);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }


        assertEquals("Marilyn Monroe",quotes.get(0).getAuthor());
    }

}
